In [1]:
import scipy.stats as stats

In [5]:
import seaborn as sns
import pandas as pd
import numpy as np
dataset = pd.read_csv('outputstatreport.csv')


In [6]:
dataset.head()

Statistical reports Legitimacy of the website
0  Among Top 10 phishing IPs                  Phishing
1  Among Top 10 phishing IPs                  Phishing
2  Among Top 10 phishing IPs                  Phishing
3  Among Top 10 phishing IPs                  Phishing
4  Among Top 10 phishing IPs                  Phishing

In [8]:
dataset_table=pd.crosstab(dataset['Statistical reports'],dataset['Legitimacy of the website'])
print(dataset_table)

Legitimacy of the website               Legitimate  Phishing
Statistical reports                                         
Among Top 10 phishing IPs                       11       330
Does not belong to top 10 Phishing IPs         489       569


In [9]:
dataset_table.values

array([[ 11, 330],
       [489, 569]], dtype=int64)

In [10]:

#Observed Values
Observed_Values = dataset_table.values 
print("Observed Values :-\n",Observed_Values)

Observed Values :-
 [[ 11 330]
 [489 569]]


In [11]:
val=stats.chi2_contingency(dataset_table)

In [12]:
val

(205.687194902985,
 1.199066301688404e-46,
 1,
 array([[121.87276626, 219.12723374],
        [378.12723374, 679.87276626]]))

In [13]:
Expected_Values=val[3]

In [14]:
no_of_rows=len(dataset_table.iloc[0:2,0])
no_of_columns=len(dataset_table.iloc[0,0:2])
ddof=(no_of_rows-1)*(no_of_columns-1)
print("Degree of Freedom:-",ddof)
alpha = 0.05

Degree of Freedom:- 1


In [15]:
from scipy.stats import chi2
chi_square=sum([(o-e)**2./e for o,e in zip(Observed_Values,Expected_Values)])
chi_square_statistic=chi_square[0]+chi_square[1]

In [16]:
print("chi-square statistic:-",chi_square_statistic)

chi-square statistic:- 207.55498434031864


In [17]:
critical_value=chi2.ppf(q=1-alpha,df=ddof)
print('critical_value:',critical_value)

critical_value: 3.841458820694124


In [18]:
#p-value
p_value=1-chi2.cdf(x=chi_square_statistic,df=ddof)
print('p-value:',p_value)
print('Significance level: ',alpha)
print('Degree of Freedom: ',ddof)
print('p-value:',p_value)

p-value: 0.0
Significance level:  0.05
Degree of Freedom:  1
p-value: 0.0
